### ISSUE TITLE
Use HTTP Ruby gem

### ISSUE THREAD

**Issue by jgarber623** [indieweb/webmention-client-ruby#13]
@aaronpk mentions some issues with HTTParty in #7. I've been using the [http](https://rubygems.org/gems/http) Ruby gem without issue. It works great and the API is fairly straightforward.

**Comment by mbajur** [comment]
What about using https://www.ruby-toolbox.com/projects/httpi so people can choose their library of choice and prevent unnecessary dependencies? :)

**Comment by jgarber623** [comment]
@mbajur Thanks for the suggestion!

I'm not familiar with that gem. Could you put together a list of pros and cons of implementing the httpi gem in this project?

**Comment by mbajur** [comment]
Well the pros are pretty obvious - people who want to use webmention-client-ruby in their project can choose and plug-in a http library of their choice through the httpi.

Regarding cons...the only one that comes to my mind is a standard one when it comes to adding a new dependency to the project - webmention-client-ruby becomes dependent on development of httpi

**Comment by Zegnat** [comment]
(For what it is worth, I did something similar in [the PHP webmention discoverer lib](https://github.com/Zegnat/php-webmention-endpoint-discovery) that was inspired by this one. It is written against [the HTTPlug interfaces](http://httplug.io) which will hopefully allow users to use whatever HTTP lib they already use for the rest of their project, rather than introducing an extra HTTP lib to their project.)

**Comment by jgarber623** [comment]
I spent some time getting familiar with HTTPI and found a few things either lacking or not immediately obvious:

- On the `Response` object, I couldn't figure out how to access the response's actual URL (after following redirects). The HTTP gem exposes a `uri` instance method on `Response` objects which is useful for parsing relative URLs in a response body.
- An HTTP `Response` object has methods for `content_type` (a Struct), `mime_type` (e.g. `text/html`, and `charset` (e.g. `utf-8`) (e.g. `text/html; charset utf-8`). Determining these values on an HTTPI `Response` object would vary depending on which (if any) adapter a user chooses to implement. The default case would mean parsing through headers using `response.headers['content-type'].split(';').first` or similar.
- Related to the above, the HTTP gem has some useful convenience methods for working with headers (most notably `headers.get`). Certainly not a dealbreaker without, but… it's handy.

So, I dunno… I appreciate what the HTTPI gem goes for, but I'm concerned the variance in adapters and the methods they expose plus the small additional burden on a user to make a decision about which adapter to use would be a net negative.

However! I'm open to being convinced otherwise. Can you point me to some other gems that implement HTTPI in a manner consistent with what you'd like to see here?

**Comment by jgarber623** [comment]
Resolved by #20.
