### ISSUE TITLE
Guard against sending a webmention for same source and target but fragment varies

### ISSUE THREAD

**Issue by jeremyf** [indieweb/webmention-client-ruby#24]
If I have a source with URL "https://takeonrules.com/" and on that page I have a link to the URL "https://takeonrules.com/#blog", the HTML Parser for mentioned_urls may need to handle the URL with the "#blog" fragment as though its the same URL.

If it still counts as a mentioned_url, consider not sending a webmention for the above source/target pair.

**Comment by jgarber623** [comment]
Ah, good catch! I'll take a swing at refactoring the HTML Parser's node selection/filtering.
