### ISSUE TITLE
adding ability to receive webmentions

### ISSUE THREAD

**Issue by bnvk** [indieweb/webmention-client-ruby#5]
@veganstraightedge I'm curious your thoughts on adding ability to receive webmentions to this gem (to used used by Rails, etc...) or is that better done as a separate gem?

**Comment by veganstraightedge** [comment]
I'm fairly indifferent but my instinct is for it to be a separate gem. Then if one wanted, wrap them both in a meta gem that only requires both. 

It would, of course, behoove the maker of a receiver gem to model the API after the sender gem.

**Comment by aaronpk** [comment]
Agreed that this would be better off as a separate gem. There's very little that sending and receiving webmentions have in common, so would be better to let them iterate development separately.
