### ISSUE TITLE
publish new version to rubygems

### ISSUE THREAD

**Issue by aaronpk** [indieweb/webmention-client-ruby#7]
my first attempt at building and installing the update breaks because of an error with httparty versions. I'll need to investigate this further. Probably will need to update the library to work with a newer httparty version.

**Comment by aarongustafson** [comment]
I upped the version in [my fork](https://github.com/aarongustafson/mention-client-ruby) to 0.15.5 and the rake tests ran without error. Wanna try building & publishing it again?

**Comment by aaronpk** [comment]
Awesome thanks. I think that worked! I just pushed version 0.1.6, want to try that out and let me know if I did that right? It's been a while since I've pushed a gem!

**Comment by aarongustafson** [comment]
Looks like it went through. Will test it now.

On a side note, it doesn’t look like the code for pingbacks is in here yet, is that right?

**Comment by aaronpk** [comment]
oh funny, you're right. The only mention of pingback in the library is a commented out section marked as "TODO".

Honestly I'd be happy if someone else took over maintaining this. I haven't used it myself in a while actually, since I switched to the PHP library and using https://telegraph.p3k.io for things.

**Comment by aarongustafson** [comment]
No worries. I was going to integrate pingback into my Jekyll plugin (as I think it’s a sensible feature request), but I could look at adding it here instead. Watch this space…

**Comment by barryf** [comment]
Thanks @aaronpk. I've updated to 0.1.6 and no issues.

**Comment by barryf** [comment]
Oh, and I'd be happy to help out with this gem. I use it for my personal site so I'm invested in ensuring it works well :)

**Comment by jgarber623** [comment]
Adding this issue to the v1.0.0 milestone for tracking purposes.

The underlying task might be to update the documentation with notes as to who currently has permissions to publish the gem to RubyGems.org (at the moment @aaronpk and I are owners).

**Comment by jgarber623** [comment]
🎉 https://rubygems.org/gems/webmention
